var oakdalestreets = {
    "Washington Ave": "131",
    "Woodford St": "78",
    "Forest Ave": "55",
    "Pleasant Ave": "54",
    "Allen Ave": "52",
    "Ocean Ave": "50",
    "Summit St": "49",
    "Maine Ave": "43",
    "Stevens Ave": "41",
    "Glenwood Ave": "41",
    "Ray St": "40",
    "Concord St": "37",
    "Clinton St": "35",
    "Wellstone Dr": "35",
    "Prospect St": "33",
    "Brentwood St": "33",
    "Northwood Dr": "33",
    "Dartmouth St": "32",
    "Alba St": "31",
    "Walton St": "31",
    "Sherwood St": "29",
    "William St": "29",
    "Pitt St": "29",
    "Auburn St": "28",
    "Codman St": "28",
    "Revere St": "27",
    "Belfort St": "27",
    "Regan Ln": "27",
    "Gleckler Rd": "27",
    "Read St": "26",
    "Virginia St": "26",
    "Hartley St": "25",
    "Fessenden St": "25",
    "Wellington Rd": "25",
    "Deering Ave": "25",
    "Longfellow St": "24",
    "Hennessey Dr": "23",
    "Edgeworth Ave": "23",
    "Murray St": "23",
    "Rackleff St": "23",
    "Deepwood Dr": "22",
    "Montrose Ave": "22",
    "Beacon St": "22",
    "Highland St": "22",
    "Pennell Ave": "22",
    "Lester Dr": "22",
    "Summit Park Ave": "22",
    "Mackworth St": "21",
    "Lawn Ave": "21",
    "Veranda St": "21",
    "Delaware Ct": "21",
    "Lane Ave": "21",
    "Noyes St": "21",
    "Columbia Rd": "21",
    "Mabel St": "20",
    "Greenwood Ln": "20",
    "Providence St": "20",
    "Ashmont St": "20",
    "Dorothy St": "19",
    "Coyle St": "18",
    "Racine Ave": "18",
    "Rosemont Ave": "18",
    "Parsons Rd": "18",
    "Carlyle Rd": "18",
    "Irving St": "17",
    "Brook Rd": "17",
    "Christy Rd": "17",
    "E Commonwealth Dr": "17",
    "Hersey St": "17",
    "Riverton Dr": "17",
    "E Kidder St": "17",
    "Plymouth St": "16",
    "Lincoln St": "16",
    "Austin St": "16",
    "Illsley St": "15",
    "Wellwood Rd": "15",
    "Newton St": "15",
    "Pineloch Dr": "15",
    "Vannah Ave": "15",
    "Norwood St": "15",
    "Tamarlane": "15",
    "Richardson St": "15",
    "Leland St": "15",
    "Woodlawn Ave": "15",
    "Back Cove Est": "15",
    "George St": "15",
    "Berkeley St": "15",
    "Torrey St": "15",
    "Harris Ave": "15",
    "Chenery St": "15",
    "Madeline St": "14",
    "Chesley Ave": "14",
    "Euclid Ave": "14",
    "Ludlow St": "14",
    "Bay View Dr": "14",
    "Tucker Ave": "14",
    "Bramblewood Dr": "14",
    "Merrymeeting Dr": "14",
    "Clifton St": "14",
    "Hicks St": "14",
    "Arcadia St": "14",
    "Brookside Rd": "13",
    "Westminster Ave": "13",
    "Broadway": "13",
    "Bradley St": "13",
    "Oakley St": "13",
    "Lexington Ave": "13",
    "Samuel Rd": "13",
    "W Commonwealth Dr": "13",
    "Ridge Rd": "13",
    "Eben Hill Dr": "13",
    "Alice St": "13",
    "Runnells St": "13",
    "Ashley Ln": "13",
    "Florida Ave": "13",
    "Frost Hill Rd": "12",
    "Huntington Ave": "12",
    "Abby Ln": "12",
    "Primrose Ln": "12",
    "Inverness St": "12",
    "Yale St": "12",
    "Mona Rd": "12",
    "Pembroke St": "12",
    "Olympia St": "12",
    "Hillis St": "12",
    "Curtis Rd": "12",
    "Edgewood Ave": "11",
    "Wellesley Ests": "11",
    "Bailey Ave": "11",
    "Maggie Ln": "11",
    "Alpine Rd": "11",
    "Wildwood Cir": "11",
    "Crosby St": "11",
    "Baxter Blvd": "11",
    "Springbrook Way": "11",
    "Falmouth St": "11",
    "Rustic Ln": "10",
    "Orland St": "10",
    "Crestview Dr": "10",
    "Skylark Rd": "10",
    "Tremont St": "10",
    "Hope Ave": "10",
    "Pya Rd": "10",
    "Dibiase St": "10",
    "Vera St": "10",
    "Sawyer St": "10",
    "Hamblet Ave": "10",
    "Belfield St": "10",
    "Loraine St": "10",
    "Stonecrest Dr": "10",
    "Aldworth St": "10",
    "Johansen St": "10",
    "Alton St": "10",
    "Shepherd Ln": "10",
    "Garsoe Dr": "10",
    "Roaring Brook Rd": "10",
    "Copley Woods Cir": "10",
    "Marlborough Rd": "9",
    "Presumpscot St": "9",
    "University St": "9",
    "Saunders St": "9",
    "Farragut St": "9",
    "Bartley Ave": "9",
    "Leonard St": "9",
    "Palmer Ave": "9",
    "Bryant St": "9",
    "Allison Ave": "9",
    "Belknap St": "9",
    "Wall St": "9",
    "Wendy Way": "9",
    "Wordsworth St": "9",
    "Farnham St": "9",
    "Bay St": "9",
    "Overset Rd": "9",
    "Riverside St": "9",
    "Olde Birch Ln": "9",
    "Bay View Ter": "9",
    "Victor Rd": "9",
    "Bedell St": "9",
    "Best St": "8",
    "Braintree St": "8",
    "Vermont Ave": "8",
    "Saugus St": "8",
    "Longview Dr": "8",
    "Hale St": "8",
    "Beverly St": "8",
    "Orkney St": "8",
    "Bramhall Ter": "8",
    "Schooner Ln": "8",
    "Continental Dr": "8",
    "Penn Ave": "8",
    "Carter St": "8",
    "Malilly Rd": "8",
    "Grafton St": "8",
    "Sturdivant Dr": "8",
    "Concord St W": "8",
    "Sumac St": "8",
    "Hall St": "7",
    "Nevens St": "7",
    "Seeley Ave": "7",
    "5Th St": "7",
    "Caron St": "7",
    "Higgins St": "7",
    "Rosedale St": "7",
    "Gable Ct": "7",
    "Milton St": "7",
    "Oakdale St": "7",
    "Watson St": "7",
    "Dole Dr": "7",
    "Berkshire Rd": "7",
    "Hawthorne St": "7",
    "Mayland St": "7",
    "W Kidder St": "7",
    "Label Ave": "7",
    "Dakota St": "7",
    "Ruby Ln": "7",
    "Epping St": "7",
    "Saint George St": "7",
    "Verrill St": "7",
    "Galvin St": "7",
    "Devonshire St": "7",
    "Vaill St": "7",
    "Hillside Rd": "7",
    "Bartlett St": "7",
    "Berwick St": "7",
    "Quaker Ln": "7",
    "Harvard St": "7",
    "Felicia Ln": "7",
    "Hodgins St": "7",
    "Jackson St": "7",
    "Westlawn Rd": "6",
    "Ashlar Ct": "6",
    "Caldwell St": "6",
    "Fall Brook St": "6",
    "Leeman St": "6",
    "Lawrence Ave": "6",
    "Braddish Ct": "6",
    "Avalon Rd": "6",
    "Fall Ln": "6",
    "Savoy St": "6",
    "Nevada Ave": "6",
    "Summer Pl": "6",
    "Mugwhy Ln": "6",
    "Cresfield Ter": "6",
    "S Grafton St": "6",
    "Berry Ave": "6",
    "Wilkie St": "6",
    "Tremaine St": "6",
    "Shingle Way": "6",
    "Arthur St": "6",
    "9Th St": "6",
    "Elmwood St": "6",
    "Amherst St": "6",
    "Demerest St": "6",
    "Cushing Ct": "6",
    "Sara Ln": "6",
    "Autumn Ln": "6",
    "Fairmount St": "6",
    "Kendall St": "6",
    "Front St": "6",
    "Lloyd Ave": "5",
    "Fisher St": "5",
    "Hillcrest W": "5",
    "Old Campus Dr": "5",
    "Cottage St": "5",
    "Liberty Way": "5",
    "Randall St": "5",
    "Clayton St": "5",
    "Eastlawn Rd": "5",
    "Homestead Ave": "5",
    "Hanson St": "5",
    "Smith Farm Ln": "5",
    "Jersey Ave": "5",
    "6Th St": "5",
    "Lynda Rd": "5",
    "Saint Jude St": "5",
    "Lambert St": "5",
    "Stuart St": "5",
    "Croquet Ln": "5",
    "Glengarden St": "5",
    "Gertrude Ave": "5",
    "Byfield Rd": "5",
    "Cottage Park Rd": "5",
    "Edgecomb Ct": "5",
    "Fieldstone Ct": "5",
    "Sylvia Rd": "5",
    "Warren Ave": "5",
    "Florence St": "5",
    "Arundel Rd": "5",
    "Holly St": "5",
    "Bernard Rd": "5",
    "Jarita Ct": "5",
    "Lennox St": "5",
    "Hollis Rd": "5",
    "Fuller St": "4",
    "Fellows St": "4",
    "Stepping Stone Ln": "4",
    "Leisure Ln": "4",
    "Waverly St": "4",
    "Kineo St": "4",
    "Oregon St": "4",
    "Old Barn Ln": "4",
    "Heather Rd": "4",
    "Braeburn Rd": "4",
    "Linden St": "4",
    "Nicholas Ct": "4",
    "Whittier St": "4",
    "8Th St": "4",
    "Panoramic View Dr": "4",
    "Deering Run Dr": "4",
    "Graystone Ln": "4",
    "Loring Ave": "4",
    "Harvard Cmn": "4",
    "Coast Ln": "4",
    "Pinewood Rd": "4",
    "Wakely Ct": "4",
    "Melody Ln": "4",
    "Meadow Ln": "4",
    "Dalton St": "4",
    "Merriam St": "4",
    "Whaleboat Rd": "4",
    "Fairfield St": "4",
    "Dresden Ct": "4",
    "Kansas Ave": "4",
    "Wendell St": "4",
    "Clapboard Rd": "4",
    "Helene St": "3",
    "Windsor Ter": "3",
    "Brookside Ln": "3",
    "Victoria St": "3",
    "Texas St": "3",
    "Cleveland St": "3",
    "Brighton Ave": "3",
    "Majors Ct": "3",
    "Fernald St": "3",
    "Wadsworth St": "3",
    "Eleanor St": "3",
    "A Apple Ledge Dr": "3",
    "Gay St": "3",
    "Mason St": "3",
    "Maplewood St": "3",
    "Settlers Ct": "3",
    "New St": "3",
    "Kenneth St": "3",
    "Clairmont Ct": "3",
    "Kimberly Ct": "3",
    "Juniper St": "3",
    "Canco Rd": "3",
    "Bismark St": "3",
    "Frigate Ln": "3",
    "Woodmere Rd": "3",
    "Barclay Ave": "3",
    "Libby St": "3",
    "Newman St": "3",
    "Pamela Rd": "3",
    "Kensington St": "3",
    "Pine Ledge Ter": "3",
    "Cypress St": "3",
    "Chapman St": "3",
    "Buca Run": "3",
    "Knight St": "3",
    "Woodbury St": "3",
    "Cummings St": "3",
    "Abbott St": "3",
    "Alice Ct": "3",
    "Humboldt St": "3",
    "Ballpark Dr": "3",
    "Briarwood Ln": "3",
    "Haskell St": "3",
    "Parsons Pond Dr": "3",
    "Castine Ave": "3",
    "W Lynne Ave": "3",
    "White Birch Ln": "3",
    "Ivaloo St": "3",
    "Patrick Way": "3",
    "Sanborn St": "3",
    "Wyndham St": "2",
    "Farm House Ln": "2",
    "Marlow St": "2",
    "Quiet Ln": "2",
    "A Carriage Ln": "2",
    "Freeman St": "2",
    "Adelaide St": "2",
    "Van Vechten St": "2",
    "Morse St": "2",
    "Jordan St": "2",
    "Iffley St": "2",
    "Hunt St": "2",
    "Churchill St": "2",
    "Drake St": "2",
    "Porch St": "2",
    "Dover Ave": "2",
    "Osprey Ter": "2",
    "Holwell St": "2",
    "Mayfield St": "2",
    "Washburn Ave": "2",
    "College St": "2",
    "Beaumont St": "2",
    "C Clairmont Ct": "2",
    "Carriage Ln": "2",
    "Feeney Way": "2",
    "Tarbell Ave": "2",
    "Congress St": "2",
    "Range St": "2",
    "King St": "2",
    "Wyoming Ave": "2",
    "Luke St": "2",
    "Frye St": "2",
    "Avalon Ter": "2",
    "Eastman Ave": "2",
    "Lynn St": "2",
    "Hingham St": "1",
    "Catherine St": "1",
    "Rivers Edge Dr": "1",
    "Dudley St": "1",
    "Sullivan St": "1",
    "James St": "1",
    "Maritime Ln": "1",
    "Hillcrest Cir": "1",
    "Havertys Way": "1",
    "Cornell St": "1",
    "Patricia Ln": "1",
    "True St": "1",
    "Birchwood Dr": "1",
    "Empire Way": "1",
    "W Presumpscot St": "1",
    "Joseph Ave": "1",
    "Fleetwood St": "1",
    "Oak St": "1",
    "Dayton St": "1",
    "Ice Pond Dr": "1",
    "Tyler St": "1",
    "Storer St": "1",
    "Matthews St": "1",
    "Morgan Ct": "1",
    "A Allen Ave": "1",
    "Bancroft St": "1",
    "Candlewyck Ter": "1",
    "A Fessenden St": "1",
    "Anthony Ave": "1",
    "Wolcott St": "1",
    "Woodmont St": "1",
    "Upland Ave": "1",
    "C Norwood St": "1",
    "R Sherwood St": "1",
    "B Carriage Ln": "1",
    "A Washington Ave": "1",
    "B Sherwood St": "1",
    "Colson Cir": "1",
    "Holiday Dr": "1",
    "A Holly St": "1",
    "Cranston St": "1",
    "Princeton St": "1",
    "R Tremont St": "1",
    "Fobes St": "1",
    "R Whittier St": "1",
    "Daggett St": "1",
    "Pheasant Hill Dr": "1",
    "Randolph St": "1",
    "Poland St": "1",
    "B Sanborn St": "1",
    "Raymond Rd": "1",
    "A Randall St": "1",
    "Bates St": "1",
    "Country Ln": "1",
    "Frederic St": "1",
    "Columbia Ter": "1",
    "Forest Cir": "1",
    "Hemingway St": "1",
    "Whitehead Cir": "1",
    "B Stevens Ave": "1",
    "Georgia St": "1",
    "Massachusetts Ave": "1",
    "Hyde St": "1",
    "Coolidge Ave": "1",
    "R Lawn Ave": "1",
    "Armstrong Hts": "1",
    "A Clairmont Ct": "1",
    "Bell St": "1",
    "Emmons St": "1",
    "Chester St": "1",
    "Deblois St": "1",
    "Toronita St": "1",
    "B Allen Ave": "1",
    "Harmony Rd": "1",
    "Jeanne St": "1",
    "Beal St": "1",
    "Commonwealth Dr": "1",
    "A William St": "1",
    "Forest Park": "1",
    "R Glengarden St": "1",
    "Bay Street Ext": "1",
    "Graham Ter": "1",
    "Goodale St": "1",
    "Pari Pl": "1",
    "Idaho St": "1",
    "Bishop St": "1",
    "View St": "1",
    "Kenwood St": "1",
    "Dingley Ct": "1",
    "Chadwick St": "1",
    "Saint Joseph St": "1",
    "B Apple Ledge Dr": "1",
    "Grace St": "1",
    "Walton Ct": "1",
    "Ledgewood Dr": "1",
    "B Clairmont Ct": "1",
    "Apple Ledge Dr": "1",
    "Hope Ln": "1",
    "Corliss Rd": "1",
    "Fernald Ter": "1",
    "Ardmore St": "1",
    "Grace Street Pl": "1",
    "Pine St": "1",
    "A Alton St": "1"
}